---
- name: Install Clickhouse
  hosts: ubuntu-clickhouse,yc-clickhouse
  roles:
    - clickhouse

- name: Install vector
  hosts: ubuntu-clickhouse,yc-clickhouse
  roles:
    - vector

- name: Install lighthouse
  hosts: ubuntu-clickhouse,yc-clickhouse
  roles:
    - lighthouse